name: Update README

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - run: go install github.com/muesli/markscribe@v0.6.0

      - run: $(go env GOPATH)/bin/markscribe templates/README.md.tpl > README.md
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - run: script/fill-recent-projects
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update generated README
          branch: master
